python parse_test_res.py your_work_path/plot-coop/output/OP_N4/caltech101/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/imagenet/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/oxford_pets/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/stanford_cars/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/oxford_flowers/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/food101/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/fgvc_aircraft/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/sun397/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/dtd/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/eurosat/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
python parse_test_res.py your_work_path/plot-coop/output/OP_N4/ucf101/FREQPL/vit_16shots/nctx4_cscFalse_ctpend --test-log
